CREATE TABLE Customer (
	ID INT IDENTITY(1,1),
	FirstName NVARCHAR(255) NOT NULL,
	LastName NVARCHAR (255) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Location (
	ID INT IDENTITY(1,1),
	Address NVARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)	
);

CREATE TABLE Product (
	ID INT IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	Price MONEY NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT CHK_Price_Nonnegative CHECK (Price > 0)
);


CREATE TABLE Inventory (
	ProductID INT NOT NULL FOREIGN KEY REFERENCES Product(ID),
	LocationID INT NOT NULL FOREIGN KEY REFERENCES Location(ID),
	Quantity INT NOT NULL,
	PRIMARY KEY (ProductID, LocationID)
	);

CREATE TABLE Orders (
	ID INT IDENTITY(1,1),
	LocationID INT NOT NULL,
	CustomerID INT NOT NULL,
	OrderTime DATETIME NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_Orders_Location_ID FOREIGN KEY (LocationID) REFERENCES Location(ID),
	CONSTRAINT FK_Orders_Customer_ID FOREIGN KEY (CustomerID) REFERENCES Customer(ID)
);

CREATE TABLE OrderDetails (
	OrderID INT NOT NULL FOREIGN KEY REFERENCES Orders(ID),
	ProductID INT NOT NULL FOREIGN KEY REFERENCES Product(ID),
	Quantity INT NULL,
	PRIMARY KEY (OrderID, ProductID)
	);
	

