CREATE TABLE Product (
	ID INT IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	Price MONEY NOT NULL,
	CONSTRAINT PK_Product PRIMARY KEY (ID),
	CONSTRAINT CHK_Price_Nonnegative CHECK (Price > 0)
);

CREATE TABLE Location (
	ID INT IDENTITY(1,1),
	Street NVARCHAR(255) NOT NULL,
	City NVARCHAR(255) NOT NULL,
	Zipcode NVARCHAR(9) NOT NULL,
	State NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_Location PRIMARY KEY (ID),
	CONSTRAINT CHK_Zipcode_CorrectDigits CHECK (LEN(Zipcode) = 5),
);


CREATE TABLE Customer (
	ID INT IDENTITY(1,1),
	FirstName NVARCHAR(255) NOT NULL,
	LastName NVARCHAR (255) NOT NULL,
	CONSTRAINT PK_Customer PRIMARY KEY (ID)
);

CREATE TABLE Orders (
	ID INT IDENTITY(1,1),
	LocationID INT NOT NULL,
	CustomerID INT NOT NULL,
	OrderTime DATETIME NOT NULL,
	CONSTRAINT PK_Orders PRIMARY KEY (ID),
	CONSTRAINT FK_Orders_Location_ID FOREIGN KEY (LocationID) REFERENCES Location(ID),
	CONSTRAINT FK_Orders_Customer_ID FOREIGN KEY (CustomerID) REFERENCES Customer(ID)
);

SELECT * FROM Location